server:
  port: 8765
eureka:  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
    
spring:
  application:
    name: gateway-server
    
zuul:
  routes:
    users:
      path: /users/**
      serviceId: user-service
      strip-prefix: false
      
endpoints:
  beans:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
  jolokia:
    enabled: true
    sensitive: false