server:
  port: 8765
  
spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone: http://localHost:8761/eureka
      
zuul:
  routes:
    users:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
